namespace: ffc-demo

serviceBusResourceGroupName: sndadpinfrg1401
serviceBusNamespaceName: sndadpinfsb1401

asoAnnotations:
  serviceoperator.azure.com/reconcile-policy: manage

namespaceTopics:
  - name: payment   
    roleAssignments:
      - roleName: 'TopicSender'

namespaceQueues:
  - name: calculation
    owner: 'no'
    roleAssignments:
      - roleName: 'QueueReceiver'

tags:
  Environment: SND1
  ServiceCode: ADP
  ServiceName: ffc-demo-calculation-service
  ServiceType: Shared
  Purpose: Define purpose
  ManagedBy: ASO
  kubernetes_cluster: SNDADPINFAK1401

#Dummy placeholder values only for linting. NOT TO BE POPULATED
subscriptionId: "dummySubscriptionId"
userAssignedIdentity: {}
teamMIPrefix: "dummy"
serviceName: "dummy"